# Generated by Django 4.0.6 on 2022-11-25 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('rightWord', models.CharField(default='right', max_length=32)),
                ('leftWord', models.CharField(default='left', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsCost', models.IntegerField(default=0)),
                ('name', models.CharField(default='ultimate device', max_length=32)),
                ('year_in_school', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=2)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('bought', models.BooleanField(default=False)),
                ('boughtAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('streak', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('hoursPlayed', models.IntegerField(default=0)),
                ('hoursWon', models.IntegerField(default=0)),
                ('highestStreak', models.IntegerField(default=0)),
                ('highestPoints', models.IntegerField(default=0)),
                ('profileAuth', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('right', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
                ('winSide', models.BooleanField(default=False)),
                ('win', models.BooleanField(default=False)),
                ('myProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.profile')),
                ('myQuiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('myProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.profile')),
                ('myStoreItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.storeitem')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('myProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.profile')),
            ],
        ),
    ]
