# Generated by Django 4.0.6 on 2022-11-25 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='created',
        ),
        migrations.AddField(
            model_name='inventory',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='isCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
