# Generated by Django 4.1.3 on 2022-11-26 00:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crossroadsBe', '0002_remove_inventory_created_inventory_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='myProfile',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='myProfile',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='myProfile',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='myQuiz',
            new_name='quiz',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='myStoreItem',
        ),
        migrations.RemoveField(
            model_name='play',
            name='win',
        ),
        migrations.RemoveField(
            model_name='play',
            name='winSide',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileAuth',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeitem',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossroadsBe.inventory'),
        ),
    ]
