# Generated by Django 4.0.6 on 2022-07-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsbe', '0002_rename_store_item_storeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='left',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='right',
        ),
        migrations.AddField(
            model_name='quiz',
            name='leftWord',
            field=models.CharField(default='right', max_length=32),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rightWord',
            field=models.CharField(default='left', max_length=32),
        ),
    ]
