# Generated by Django 4.0.6 on 2022-07-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsbe', '0003_remove_quiz_left_remove_quiz_right_quiz_leftword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='leftWord',
            field=models.CharField(default='left', max_length=32),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='rightWord',
            field=models.CharField(default='right', max_length=32),
        ),
    ]
