# Generated by Django 4.1.3 on 2022-11-26 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0003_rename_myprofile_feedback_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='left',
        ),
        migrations.RemoveField(
            model_name='play',
            name='right',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='boughtAt',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='created',
        ),
        migrations.AddField(
            model_name='play',
            name='choice',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='Left', max_length=5),
        ),
        migrations.CreateModel(
            name='InvetoryStoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boughtAt', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.inventory')),
                ('storeItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.storeitem')),
            ],
        ),
    ]
