# Generated by Django 4.1.3 on 2022-11-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0004_remove_play_left_remove_play_right_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='isCreated',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='used',
        ),
    ]
