# Generated by Django 4.0.6 on 2022-07-28 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crossroadsBe', '0004_alter_quiz_leftword_alter_quiz_rightword'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileAuth',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='itemId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
