# Generated by Django 4.1.3 on 2022-11-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0005_remove_inventory_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='inventory',
        ),
    ]
