# Generated by Django 4.0.6 on 2022-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0005_profile_profileauth_storeitem_itemid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='itemId',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='name',
            field=models.CharField(default='ultimate device', max_length=32),
        ),
    ]
