# Generated by Django 4.1.3 on 2022-11-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0006_remove_storeitem_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='year_in_school',
            new_name='powerLevel',
        ),
    ]
