# Generated by Django 4.0.6 on 2022-07-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0006_remove_storeitem_itemid_storeitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='itemId',
            field=models.IntegerField(default=0),
        ),
    ]
