# Generated by Django 4.0.6 on 2022-07-28 17:37

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0007_storeitem_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='itemId',
            field=models.IntegerField(default=builtins.id),
        ),
    ]
