# Generated by Django 4.0.6 on 2022-07-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsbe', '0008_alter_storeitem_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='itemId',
        ),
    ]
