# Generated by Django 4.1.3 on 2022-11-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0008_remove_quiz_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
