# Generated by Django 4.0.6 on 2022-07-29 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0009_remove_storeitem_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plays',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
