# Generated by Django 4.1.3 on 2022-11-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0009_quiz_ended'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvetoryStoreItem',
            new_name='InventoryStoreItem',
        ),
    ]
