# Generated by Django 4.0.6 on 2022-11-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsbe', '0012_alter_fact_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='text',
            new_name='title',
        ),
    ]
