# Generated by Django 4.0.6 on 2023-02-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0012_alter_feedback_author_alter_inventory_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='highestPoints',
            new_name='highestStreakRank',
        ),
    ]
