# Generated by Django 4.0.6 on 2023-02-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0013_rename_highestpoints_profile_higheststreakrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='description',
            field=models.TextField(default='a random device', max_length=300),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='img',
            field=models.URLField(default='https://images.unsplash.com/photo-1538032746644-0212e812a9e7?auto=format&fit=crop&w=400&h=250&q=60', max_length=999),
        ),
    ]
