# Generated by Django 4.0.6 on 2022-11-13 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsbe', '0013_rename_text_fact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highestPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='highestStreak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hoursPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hoursWon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='boughtAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
