# Generated by Django 4.0.6 on 2023-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0014_storeitem_description_storeitem_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='ended',
        ),
        migrations.AlterField(
            model_name='play',
            name='choice',
            field=models.CharField(choices=[('Right', 'Left'), ('Left', 'Right')], default='Left', max_length=5),
        ),
    ]
