# Generated by Django 4.0.6 on 2022-11-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsbe', '0014_profile_highestpoints_profile_higheststreak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='boughtAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
