# Generated by Django 4.1.7 on 2023-08-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0015_remove_quiz_ended_alter_play_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateField(auto_now_add=True, unique_for_date=True),
        ),
    ]
