# Generated by Django 4.0.6 on 2022-11-25 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0015_storeitem_bought_alter_storeitem_boughtat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='myProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.profile'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='myProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.profile'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='myStoreItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.storeitem'),
        ),
        migrations.AlterField(
            model_name='play',
            name='myProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.profile'),
        ),
        migrations.AlterField(
            model_name='play',
            name='myQuiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossroadsBe.quiz'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='pointsCost',
            field=models.IntegerField(default=0),
        ),
    ]
