# Generated by Django 4.1.7 on 2023-08-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0016_alter_quiz_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
