# Generated by Django 4.0.6 on 2022-11-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0016_alter_feedback_myprofile_alter_inventory_myprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='winSide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='play',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
