# Generated by Django 4.0.6 on 2022-11-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0017_play_ended_play_winside_alter_play_win_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
