# Generated by Django 4.0.6 on 2022-11-25 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crossroadsBe', '0019_alter_feedback_created_alter_inventory_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 25, 20, 23, 2, 834697, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 25, 20, 23, 18, 485867, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='play',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 25, 20, 23, 26, 278916, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 25, 20, 23, 32, 90825, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 25, 20, 23, 39, 733310, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 25, 20, 23, 45, 386455, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
